// Finding 7: Excessive Cyclomatic Complexity
public int calculate(int a, int b, String op) {
    if (op.equals("ADD")) {
        // ...
    } else if (op.equals("SUB")) {
        // ...
    } else if (op.equals("MUL")) {
        // ...
    } else if (op.equals("DIV")) {
        // ...
    } else {
        // ...
    }
    // ... 30+ lines of nested logic
}
